spring:
  application:
    name: servicio-hoteles

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: admin
    password:
  
  sql:
    init:
      mode: always 

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    show-sql: true
    defer-datasource-initialization: true

# Config de el servidor  
server: 
  port: 8000

eureka: 
  client:
    serviceUrl:
      # Direccion a la que se conecta el microservicio con eureka
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost